-- REVISING I
SELECT *
FROM CITY
WHERE POPULATION > 100000 AND COUNTRYCODE = "USA";

-- REVISING II
SELECT NAME
FROM CITY
WHERE POPULATION > 120000 AND COUNTRYCODE = "USA";

-- SELECT ALL 
SELECT *
FROM CITY;

-- SELECT BY ID
SELECT *
FROM CITY
WHERE ID = 1661;

-- JAPANESE CITIES' ATTRIBUTES
SELECT *
FROM CITY
WHERE COUNTRYCODE = "JPN";

-- JAPANESE CITIES' NAMES
SELECT NAME
FROM CITY
WHERE COUNTRYCODE = "JPN";
