-- REVISING I
SELECT *
FROM CITY
WHERE POPULATION > 100000 AND COUNTRYCODE = "USA";

-- REVISING II
SELECT NAME
FROM CITY
WHERE POPULATION > 120000 AND COUNTRYCODE = "USA";

-- SELECT ALL
SELECT *
FROM CITY;

-- SELECT BY ID
SELECT *
FROM CITY
WHERE ID = 1661;

-- JAPANESE CITIES' ATTRIBUTES
SELECT *
FROM CITY
WHERE COUNTRYCODE = "JPN";

-- JAPANESE CITIES' NAMES
SELECT NAME
FROM CITY
WHERE COUNTRYCODE = "JPN";

-- WEATHER OBSERVATION STATION 1
SELECT CITY, STATE
FROM STATION;

-- WEATHER OBSERVATION STATION 3
SELECT DISTINCT CITY
FROM STATION
WHERE ID % 2 = 0;

-- WEATHER OBSERVATION STATION 4
SELECT COUNT(CITY) - COUNT(DISTINCT CITY)
FROM STATION;

--- WEATHER OBSERVATION STATION 5
SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY),
CITY LIMIT 1;

SELECT CITY, LENGTH(CITY)
FROM STATION
ORDER BY LENGTH(CITY) DESC,
CITY LIMIT 1;

-- WEATHER OBSERVATION STATION 6
-- look into using REGEXP if time
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE "a%" OR CITY LIKE "e%" OR CITY LIKE "i%" OR CITY LIKE "o%" OR CITY LIKE "u%";

-- WEATHER OBSERVATION STATION 7
SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE "%a" OR CITY LIKE "%e" OR CITY LIKE "%i" OR CITY LIKE "%o" OR CITY LIKE "%u";

-- WEATHER OBSERVATION STATION 8
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[aeiou].*[aeiou]$';

-- WEATHER OBSERVATION STATION 9
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[^aeiou]';

-- WEATHER OBSERVATION STATION 10
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '[^aeiou]$';

-- WEATHER OBSERVATION STATION 11
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[^aeiou].*|[^aeiou]$';

-- WEATHER OBSERVATION STATION 12
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[^aeiou].*[^aeiou]$';

-- HIGHER THAN 75 MARKS
